name: CI Pipeline
on:
  pull_request:
    branches:
      - main
    paths:
      - 'src/**'
  push:
    branches:
      - main
    paths:
      - 'src/**'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install Java
        uses: actions/setup-java@v4
        with:
          java-version: '23'
          distribution: 'oracle'
      - name: Run Maven
        run: mvn clean install
      - name: Run Tests
        run: mvn test