name: CI Pipeline
on:
  pull_request:
    branches:
      - main
    paths:
      - 'src/**'
  push:
jobs:
  checkstyle:
    name: checkstyle
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          java-version: '23'
          distribution: 'oracle'
      - uses: dbelyaev/action-checkstyle@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          reporter: github-pr-review
          checkstyle_config: google_checks.xml
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install Java
        uses: actions/setup-java@v4
        with:
          java-version: '23'
          distribution: 'oracle'
      - name: Run Maven
        run: mvn clean install
      - name: Run Tests
        run: mvn test