name: Pipeline Check
on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  show-message:
    runs-on: ubuntu-latest
    steps:
      - name: Pipeline Message
        run: echo "Pipeline Iniciado com sucesso!"